In [2]:
import numpy as np

print(np.__version__)

1.21.4


In [3]:
# 리스트를 이용해서 numpy 생성
ar1 = np.array([1, 2, 3, 4, 5])
print('ar1 >>> : ', ar1)
print('ar1 >>> : ', type(ar1))

ar1 >>> :  [1 2 3 4 5]
ar1 >>> :  <class 'numpy.ndarray'>


In [5]:
ar2 = np.array([[10, 20, 30], [40, 50, 60]])
print('ar2 >>> : ')
print(ar2)
print('ar2 >>> : ', type(ar2))

ar2 >>> : 
[[10 20 30]
 [40 50 60]]
ar2 >>> :  <class 'numpy.ndarray'>


In [6]:
# 값의 범위를 지정하여 numpy 생성 : np.arange(시작값, 끝값, 간격)
ar3 = np.arange(1, 11, 2)
print('ar3 >>> : ', ar3)

ar3 >>> :  [1 3 5 7 9]


In [8]:
# 구조를 지정하여 numpy 생성 : np.array().reshape()
ar4 = np.array([1 ,2 , 3, 4, 5, 6]).reshape((3, 2))
print('ar4 >>> : ')
print(ar4)

ar4 >>> : 
[[1 2]
 [3 4]
 [5 6]]


In [10]:
# 초기값과 구조를 지정하여 numpy 생성
ar5 = np.zeros((2, 3))
print('ar5 >>> : ')
print(ar5)

ar5 >>> : 
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# numpy 슬라이싱
print('ar2 >>> : ')
print(ar2)
ar6 = ar2[0:2, 0:2]
print('ar6 >>> : ')
print(ar6)

ar2 >>> : 
[[10 20 30]
 [40 50 60]]
ar6 >>> : 
[[10 20]
 [40 50]]


In [15]:
ar7 = ar2[0, :]
print('ar7 >>> : ', ar7)

ar7 >>> :  [10 20 30]


In [16]:
# numpy 사칙연산
print('ar1 >>> : ', ar1)
ar8 = ar1 + 10
print('ar8 >>> : ', ar8)

ar1 >>> :  [1 2 3 4 5]
ar8 >>> :  [11 12 13 14 15]


In [18]:
# ++++++++++++++++++++
print('ar1 + ar8 >>>>> ')
print('ar1 >>> : ', ar1)
print('ar8 >>> : ', ar8)
aa1 = ar1 + ar8
print('aa1 >>> : ', aa1)

ar1 + ar8 >>>>> 
ar1 >>> :  [1 2 3 4 5]
ar8 >>> :  [11 12 13 14 15]
aa1 >>> :  [12 14 16 18 20]


In [19]:
# --------------------
print('ar8 - ar1 >>>>> ')
print('ar8 >>> : ', ar8)
print('ar1 >>> : ', ar1)
aa1 = ar8 - ar1
print('aa1 >>> : ', aa1)

ar8 - ar1 >>>>> 
ar8 >>> :  [11 12 13 14 15]
ar1 >>> :  [1 2 3 4 5]
aa1 >>> :  [10 10 10 10 10]


In [20]:
# ********************
print('ar8 * 2 >>>>> ')
print('ar8 >>> : ', ar8)
aa1 = ar8 * 2
print('aa1 >>> : ', aa1)

ar8 * 2 >>>>> 
ar8 >>> :  [11 12 13 14 15]
aa1 >>> :  [22 24 26 28 30]


In [21]:
# ////////////////////
print('ar8 / 2 >>>>> ')
print('ar8 >>> : ', ar8)
aa1 = ar8 / 2
print('aa1 >>> : ', aa1)

ar8 / 2 >>>>> 
ar8 >>> :  [11 12 13 14 15]
aa1 >>> :  [5.5 6.  6.5 7.  7.5]


In [24]:
# numpy 행렬곱 연산 : np.dot()
print('ar2 >>> : ')
print(ar2)
print('ar4 >>> : ')
print(ar4)
ar9 = np.dot(ar2, ar4)
print('ar9 >>> : ')
print(ar9)

ar2 >>> : 
[[10 20 30]
 [40 50 60]]
ar4 >>> : 
[[1 2]
 [3 4]
 [5 6]]
ar9 >>> : 
[[220 280]
 [490 640]]
